apiVersion: v2
name: openmaxio-console
description: OpenMaxIO Object Browser - Enhanced MinIO admin console
type: application
version: 1.7.6
appVersion: "1.7.6"
maintainers:
  - name: Remodl AI
    email: brian@remodl.ai
